language: r

r:
  - release
  - devel
  - oldrel
 
cache: packages

sudo: required

dist: trusty

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
       sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes;
       sudo apt-get --yes --force-yes update -qq;
       sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev;
    else 
       brew_packages: libgit2;
    fi

warnings_are_errors: true

r_packages:
  - devtools
  
r_github_packages:
  - r-lib/covr
  - dkahle/ggmap
  
after_success:
  - Rscript -e 'covr::codecov()'
