# Download script file from GitHub
init:
  ps: |
        Get-Date
        $ErrorActionPreference = "Stop"

install:
  ps: |
        Import-Module '.\scripts\appveyor-tool.ps1'
        Bootstrap

# Adapt as necessary starting from here

environment:
 USE_RTOOLS: true

 global:
    R_REMOTES_STANDALONE: true
    WARNINGS_ARE_ERRORS: 1

 matrix:
  - R_VERSION: devel
    GCC_PATH: mingw_32

  - R_VERSION: devel
    R_ARCH: x64
    GCC_PATH: mingw_64

  - R_VERSION: release
    R_ARCH: x64

  - R_VERSION: stable

build_script:
  - travis-tool.sh install_deps
  - travis-tool.sh github_package r-lib/covr
  - travis-tool.sh github_package dkahle/ggmap

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

on_success:
  - Rscript -e 'covr::codecov()'
  
 GITHUB_PAT:
    secure: SCSbqeoITOpmrsoAuZB3tfGrW/YJG6fB+ohVvP/WUaTWGPPx3NnQ6J4WWDwXew9j  

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
